# Use a imagem base do Laragon com PHP
FROM php:latest

# Configure o diretório de trabalho no contêiner
WORKDIR /laragon/www/html

# Copie os arquivos do seu aplicativo para o contêiner
COPY . .

# Exponha a porta do servidor PHP (geralmente 80)
EXPOSE 80

# Comando para iniciar o servidor PHP
CMD ["php", "-S", "0.0.0.0:80"]